import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/header/Header";
import Footer from "./Components/footer/Footer";

export const metadata: Metadata = {
  title: "LUXE | Luxury Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <header className="fixed w-full bg-white z-50 border-b border-gray-100">
          <Header/>
        </header>
        <main className="bg-[#F8F8F8]">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
